version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    restart: unless-stopped
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
  postgres:
    image: postgres:latest
    ports:
        - 5433:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: webapp
        POSTGRES_USER: root
volumes:
  postgres_data: