version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      - backend
    environment:
      - db_user=${db_user}
      - db_password=${db_password}
      - db_host=${db_host}
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - frontend
      - backend
  postgres:
    image: postgres:latest
    ports:
        - 5433:5432
    restart: unless-stopped
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_PASSWORD=${db_user}
      - POSTGRES_USER=${db_password}
    networks:
      - db
      - backend
volumes:
  postgres_data:
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
    db:
        driver: bridge
        internal: true